#!/usr/bin/env python3

import logging

from core.reptor import Reptor


log = logging.getLogger("reptor")
logging.basicConfig(format="%(message)s")
log.setLevel(logging.INFO)

# TODO better error message if settings are missing

if __name__ == "__main__":
    reptor = Reptor()

    reptor.run()
