site_name: "reptor Docs"
site_url: "https://reptor.github.io/"
repo_url: https://github.com/syslifters/reptor/
site_dir: ./site/ # Where to put the HTML files

nav:
  - Home: index.md
  - Library :
    - Overview : lib/overview.md
    - Reptor : lib/reptor.md
    - Importers : lib/importers.md
    - Plugins : lib/plugins.md
    - Logging : lib/logging.md
    - Config : lib/config.md
    - Testing : lib/tests.md
  - API Models: api-models.md
  - Core Plugins:
    - core-modules.md
    - translate.md
  - Community Plugins:
    - Create Plugin : community/create.md
    - Nikto : community/nikto.md
    - OWASPZap : community/owaspzap.md

theme:
  name: material
  #logo: images/logo.svg TODO
  features:
    - content.code.annotate
    - search.share
    #- navigation.expand
  palette:
    - scheme: default
  theme:
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/question-16

extra_css:
  - stylesheets/extra.css
  - stylesheets/hint.min.css

watch:
  - ..

plugins:
  #- social:
  #    cards: !ENV [CARDS, true]
  #    cards_color:
  #      fill: "#001827"
  #      text: "#F9FDFF"
  #    cards_font: Exo
  # - tooltips
  - search
  #- mkdocstrings:
  #    handlers:
  #        python:
  #          paths: [..]
  #          options:
  #            show_bases: true
  #            show_docstring_attributes: true
  #            docstring_section_style: list
  #            show_root_heading: true
  #            heading_level: 2
  #- privacy

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sysreptor
    - icon: fontawesome/brands/linkedin
      link: https://at.linkedin.com/showcase/sysreptor
  generator: false

#copyright: '<a href="https://www.syslifters.com/" target="_blank">Our Website</a> | <a href="https://www.syslifters.com/impressum" target="_blank">Imprint</a> | <a href="/data-privacy">Data Privacy</a> | <a href="https://docs.syslifters.com/contact-us" target="blank">Contact</a><br><br>Die FFG ist die zentrale nationale Förderorganisation und stärkt Österreichs Innovationskraft.<br>Dieses Projekt wird aus Mitteln der FFG gefördert. <a href="https://www.ffg.at" target="_blank">www.ffg.at</a><br>'
