name: docs unittests
run-name: unittests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - run: cd docs
    - run: pip install -r requirements.txt
    - run: mkdocs build
