name: generate help messages
run-name: help-messages
on: [push]
env:
  plugins: 'nmap nikto zap sslyze file note projects templates translate ghostwriter projects'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - run: pip install .[all]
    - run: |
        reptor --help | tee docs/help-messages/reptor
        for p in $plugins; do
          reptor "$p" --help | tee docs/help-messages/"$p"
        done
    - uses: EndBug/add-and-commit@v9.1.3
      with:
        add: 'docs/help-messages/'
        author_name: License Bot
        author_email: hello@syslifters.com
        message: 'Update help messages'
