name: generate-docs
run-name: help-messages
on:
  push:
    branches:
      - 'main'
env:
  plugins: 'findingfromtemplate burp openvas qualys nessus nmap zap createproject pushproject unpackarchive packarchive sslyze file note project template translate ghostwriter finding deletefindings deleteprojects exportfindings defectdojo'
jobs:
  help-messages:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install .[all]
    - run: |
        reptor --help > docs/help-messages/reptor
        for p in $plugins; do
          reptor "$p" --help > docs/help-messages/"$p"
        done
    - uses: EndBug/add-and-commit@v9.1.3
      with:
        add: 'docs/help-messages/'
        pull: "--autostash"
        author_name: Help Message Bot
        author_email: hello@syslifters.com
        message: 'Update help messages'

  update-readme:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: cat docs/getting-started.md | sed "/## Usage/q" > README.md
    - run: |
        printf "\n\`\`\`" >> README.md
        cat docs/help-messages/reptor >> README.md
        printf "\n\`\`\`" >> README.md
    - uses: EndBug/add-and-commit@v9.1.3
      with:
        add: 'README.md'
        author_name: README Bot
        author_email: hello@syslifters.com
        message: 'Update README.md'
