name: generate license notice file
run-name: licenses
on: [push]
jobs:
  generate:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install pip-licenses
    - run: pip install .
    - run: bash ./generate_notice.sh
    - uses: EndBug/add-and-commit@v9.1.3
      with:
        add: 'NOTICE'
        pull: "--autostash"
        author_name: License Bot
        author_email: hello@syslifters.com
        message: 'Update NOTICE file'
