name: create release
run-name: release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python3 -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist/

  publish:
    runs-on: ubuntu-22.04
    needs: build
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: 
      name: release
      url: https://pypi.org/p/reptor
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/download-artifact@master
      with:
        name: dist
        path: dist/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
